# Generated by Django 5.0.1 on 2024-01-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key_Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident', models.CharField(max_length=100)),
                ('check_in', models.TimeField(auto_now_add=True)),
                ('check_out', models.TimeField(null=True)),
            ],
        ),
    ]
